services:
  backend:
    build: ./django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-app:/app
    ports:
      - "8000:8000"
  client:
    build: ./react-app
    volumes:
      - ./react-app:/app
      - node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm start
    ports:
      - "3001:3000"

  db:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "8001:8001"

volumes:
  node_modules:
  db_vol:
  db_config:

    